USE [master]
GO

/****** Object:  Database [alexandr_gorbunov_]    Script Date: 31-Jan-17 6:00:44 PM ******/
CREATE DATABASE [alexandr_gorbunov_]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'alexandr_gorbunov_', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\alexandr_gorbunov_.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'alexandr_gorbunov__log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\alexandr_gorbunov__log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [alexandr_gorbunov_] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [alexandr_gorbunov_].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [alexandr_gorbunov_] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET ARITHABORT OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [alexandr_gorbunov_] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [alexandr_gorbunov_] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET  DISABLE_BROKER 
GO

ALTER DATABASE [alexandr_gorbunov_] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [alexandr_gorbunov_] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET RECOVERY FULL 
GO

ALTER DATABASE [alexandr_gorbunov_] SET  MULTI_USER 
GO

ALTER DATABASE [alexandr_gorbunov_] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [alexandr_gorbunov_] SET DB_CHAINING OFF 
GO

ALTER DATABASE [alexandr_gorbunov_] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [alexandr_gorbunov_] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [alexandr_gorbunov_] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [alexandr_gorbunov_] SET QUERY_STORE = OFF
GO

USE [alexandr_gorbunov_]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [alexandr_gorbunov_] SET  READ_WRITE 
GO


